package main

type challengeSeed struct {
	Title        string
	Description  string
	StarterCode  string
	Language     string
	Difficulty   string
	Category     string
	Tags         []string
}

var challengeSeeds = []challengeSeed{
	{
		Title:       "Binary Search Implementation",
		Description: "Implement a binary search algorithm that finds the index of a target value in a sorted array. Return -1 if not found.",
		StarterCode: "function binarySearch(arr, target) {\n  // TODO: implement binary search\n  return -1;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"search", "arrays", "divide-and-conquer"},
	},
	{
		Title:       "Reverse a String",
		Description: "Write a function that reverses a given string in-place without using built-in reverse methods.",
		StarterCode: "function reverseString(str) {\n  // TODO: reverse the string\n  return str;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"strings", "manipulation"},
	},
	{
		Title:       "Check for Palindrome",
		Description: "Implement a function that checks if a given string is a palindrome (reads the same forwards and backwards). Ignore case and non-alphanumeric characters.",
		StarterCode: "function isPalindrome(str) {\n  // TODO: check if palindrome\n  return false;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"strings", "validation"},
	},
	{
		Title:       "Find Maximum in Array",
		Description: "Write a function to find the maximum value in an array of numbers without using Math.max.",
		StarterCode: "function findMax(arr) {\n  // TODO: find maximum value\n  return 0;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"arrays", "iteration"},
	},
	{
		Title:       "Count Vowels",
		Description: "Implement a function that counts the number of vowels (a, e, i, o, u) in a given string. Case-insensitive.",
		StarterCode: "function countVowels(str) {\n  // TODO: count vowels\n  return 0;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"strings", "counting"},
	},
	{
		Title:       "Merge Two Sorted Arrays",
		Description: "Merge two sorted arrays into a single sorted array. Optimize for O(n+m) time complexity.",
		StarterCode: "function mergeSortedArrays(arr1, arr2) {\n  // TODO: merge sorted arrays\n  return [];\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "algorithm",
		Tags:        []string{"arrays", "sorting", "merge"},
	},
	{
		Title:       "Valid Parentheses",
		Description: "Check if a string containing only parentheses, brackets, and braces is valid. Open brackets must be closed in the correct order.",
		StarterCode: "function isValidParentheses(str) {\n  // TODO: validate parentheses\n  return false;\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "algorithm",
		Tags:        []string{"stack", "strings", "validation"},
	},
	{
		Title:       "FizzBuzz",
		Description: "Print numbers from 1 to n, but print 'Fizz' for multiples of 3, 'Buzz' for multiples of 5, and 'FizzBuzz' for multiples of both.",
		StarterCode: "function fizzBuzz(n) {\n  // TODO: implement fizzbuzz\n  return [];\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"conditionals", "iteration"},
	},
	{
		Title:       "Deep Clone Object",
		Description: "Implement a deep clone function for nested objects without using JSON.parse/stringify.",
		StarterCode: "function deepClone(obj) {\n  // TODO: deep clone object\n  return obj;\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "utility",
		Tags:        []string{"objects", "recursion", "cloning"},
	},
	{
		Title:       "Debounce Function",
		Description: "Implement a debounce function that delays invoking a function until after wait milliseconds have elapsed since the last invocation.",
		StarterCode: "function debounce(func, wait) {\n  // TODO: implement debounce\n  return func;\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "utility",
		Tags:        []string{"functions", "timing", "performance"},
	},
	{
		Title:       "Implement a Queue",
		Description: "Create a Queue class with enqueue, dequeue, peek, and isEmpty methods using only arrays.",
		StarterCode: "class Queue {\n  constructor() {\n    // TODO: initialize\n  }\n  enqueue(item) {}\n  dequeue() {}\n  peek() {}\n  isEmpty() {}\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "data-structure",
		Tags:        []string{"queue", "class", "data-structure"},
	},
	{
		Title:       "Implement a Stack",
		Description: "Create a Stack class with push, pop, peek, and isEmpty methods using only arrays.",
		StarterCode: "class Stack {\n  constructor() {\n    // TODO: initialize\n  }\n  push(item) {}\n  pop() {}\n  peek() {}\n  isEmpty() {}\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "data-structure",
		Tags:        []string{"stack", "class", "data-structure"},
	},
	{
		Title:       "Linked List Node",
		Description: "Implement a LinkedList class with append, prepend, and delete methods. Each node should have a value and next pointer.",
		StarterCode: "class ListNode {\n  constructor(val) {\n    this.val = val;\n    this.next = null;\n  }\n}\n\nclass LinkedList {\n  constructor() {\n    this.head = null;\n  }\n  append(val) {}\n  prepend(val) {}\n  delete(val) {}\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "data-structure",
		Tags:        []string{"linked-list", "class", "data-structure"},
	},
	{
		Title:       "Two Sum",
		Description: "Given an array of integers and a target sum, return indices of the two numbers that add up to the target. Optimize for O(n) time.",
		StarterCode: "function twoSum(nums, target) {\n  // TODO: find two sum\n  return [];\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"arrays", "hash-map", "search"},
	},
	{
		Title:       "Longest Substring Without Repeating Characters",
		Description: "Find the length of the longest substring without repeating characters in a given string.",
		StarterCode: "function lengthOfLongestSubstring(s) {\n  // TODO: find longest substring\n  return 0;\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "algorithm",
		Tags:        []string{"strings", "sliding-window", "hash-set"},
	},
	{
		Title:       "Validate Binary Search Tree",
		Description: "Determine if a binary tree is a valid binary search tree. The left subtree must contain values less than the node, and the right subtree must contain values greater.",
		StarterCode: "function isValidBST(root) {\n  // TODO: validate BST\n  return false;\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "data-structure",
		Tags:        []string{"binary-tree", "recursion", "validation"},
	},
	{
		Title:       "Implement LRU Cache",
		Description: "Create an LRU (Least Recently Used) cache with get and put methods. The cache should have a fixed capacity and evict the least recently used item when full.",
		StarterCode: "class LRUCache {\n  constructor(capacity) {\n    // TODO: initialize\n  }\n  get(key) {}\n  put(key, value) {}\n}",
		Language:    "javascript",
		Difficulty:  "hard",
		Category:    "data-structure",
		Tags:        []string{"cache", "hash-map", "linked-list"},
	},
	{
		Title:       "Flatten Nested Array",
		Description: "Write a function that flattens a nested array structure into a single-level array. Handle arbitrary nesting depth.",
		StarterCode: "function flatten(arr) {\n  // TODO: flatten nested array\n  return [];\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "utility",
		Tags:        []string{"arrays", "recursion", "transformation"},
	},
	{
		Title:       "Implement Promise.all",
		Description: "Recreate the Promise.all behavior that takes an array of promises and resolves when all resolve, or rejects if any reject.",
		StarterCode: "function promiseAll(promises) {\n  // TODO: implement Promise.all\n  return Promise.resolve([]);\n}",
		Language:    "javascript",
		Difficulty:  "hard",
		Category:    "system-design",
		Tags:        []string{"promises", "async", "concurrency"},
	},
	{
		Title:       "Event Emitter",
		Description: "Create an EventEmitter class with on, off, and emit methods for managing event listeners.",
		StarterCode: "class EventEmitter {\n  constructor() {\n    // TODO: initialize\n  }\n  on(event, callback) {}\n  off(event, callback) {}\n  emit(event, data) {}\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "system-design",
		Tags:        []string{"events", "observer-pattern", "class"},
	},
	{
		Title:       "Fix the Async Bug",
		Description: "The following async function has a bug where it doesn't wait for the data to load before returning. Fix it without using async/await syntax.",
		StarterCode: "function loadData(callback) {\n  let result = null;\n  fetch('/api/data')\n    .then(res => res.json())\n    .then(data => {\n      result = data;\n    });\n  return callback(result);\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "bugfix",
		Tags:        []string{"async", "promises", "bugfix"},
	},
	{
		Title:       "Fix the Loop Closure",
		Description: "The following loop has a closure bug where all callbacks log the same value. Fix it without changing the loop structure.",
		StarterCode: "for (var i = 0; i < 5; i++) {\n  setTimeout(() => {\n    console.log(i);\n  }, 100);\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "bugfix",
		Tags:        []string{"closures", "loops", "scope"},
	},
	{
		Title:       "Fix the Object Mutation",
		Description: "The following code accidentally mutates the original object. Fix it to create a proper copy.",
		StarterCode: "function updateUser(user, updates) {\n  const updated = user;\n  updated.name = updates.name;\n  updated.email = updates.email;\n  return updated;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "bugfix",
		Tags:        []string{"objects", "mutation", "bugfix"},
	},
	{
		Title:       "Throttle Function",
		Description: "Implement a throttle function that ensures a function is called at most once every wait milliseconds, unlike debounce which resets on each call.",
		StarterCode: "function throttle(func, wait) {\n  // TODO: implement throttle\n  return func;\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "utility",
		Tags:        []string{"functions", "timing", "performance"},
	},
	{
		Title:       "Group Anagrams",
		Description: "Given an array of strings, group the anagrams together. Anagrams are words with the same characters in different orders.",
		StarterCode: "function groupAnagrams(strs) {\n  // TODO: group anagrams\n  return [];\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "algorithm",
		Tags:        []string{"strings", "hash-map", "sorting"},
	},
	{
		Title:       "Implement a Set",
		Description: "Create a Set class with add, has, delete, and size methods using only objects. Do not use the built-in Set.",
		StarterCode: "class Set {\n  constructor() {\n    // TODO: initialize\n  }\n  add(value) {}\n  has(value) {}\n  delete(value) {}\n  get size() {}\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "data-structure",
		Tags:        []string{"set", "class", "data-structure"},
	},
	{
		Title:       "Binary Tree Level Order Traversal",
		Description: "Given a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level).",
		StarterCode: "function levelOrder(root) {\n  // TODO: level order traversal\n  return [];\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "data-structure",
		Tags:        []string{"binary-tree", "bfs", "traversal"},
	},
	{
		Title:       "Rate Limiter",
		Description: "Implement a rate limiter that allows n requests per time window. Return true if request is allowed, false otherwise.",
		StarterCode: "class RateLimiter {\n  constructor(maxRequests, windowMs) {\n    // TODO: initialize\n  }\n  allow() {\n    // TODO: check rate limit\n  }\n}",
		Language:    "javascript",
		Difficulty:  "hard",
		Category:    "system-design",
		Tags:        []string{"rate-limiting", "time-window", "middleware"},
	},
	{
		Title:       "Find Missing Number",
		Description: "Given an array containing n distinct numbers from 0 to n, find the missing number. Solve in O(n) time and O(1) space.",
		StarterCode: "function findMissingNumber(nums) {\n  // TODO: find missing number\n  return -1;\n}",
		Language:    "javascript",
		Difficulty:  "easy",
		Category:    "algorithm",
		Tags:        []string{"arrays", "math", "bitwise"},
	},
	{
		Title:       "Implement a Simple Pub/Sub",
		Description: "Create a Pub/Sub system with subscribe, unsubscribe, and publish methods. Subscribers should receive messages for topics they're subscribed to.",
		StarterCode: "class PubSub {\n  constructor() {\n    // TODO: initialize\n  }\n  subscribe(topic, callback) {}\n  unsubscribe(topic, callback) {}\n  publish(topic, message) {}\n}",
		Language:    "javascript",
		Difficulty:  "medium",
		Category:    "system-design",
		Tags:        []string{"pub-sub", "events", "messaging"},
	},
}